[env:pico]
platform = raspberrypi
board = pico
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ST7735 and ST7789 Library
